### ISSUE TITLE
[BUG]: viewing the website on Linux firefox displays nothing to the screen

### ISSUE THREAD

**Issue by kyubxy** [techlauncher-mlai-edge-physics/CFlowSim#126]
**Describe the bug**
When I access the website (ie. through the deployment link) I get a blank screen. The following is also printed to the console
```
Uncaught DOMException: WebGPU is not yet available in Release or Beta builds.
    <anonymous> https://techlauncher-mlai-edge-physics.github.io/assets/index-22f3bb6f.js:4096
[index-22f3bb6f.js:4096](https://techlauncher-mlai-edge-physics.github.io/assets/index-22f3bb6f.js)
    <anonymous> https://techlauncher-mlai-edge-physics.github.io/assets/index-22f3bb6f.js:4096
```

**To Reproduce**

1. Use firefox on linux
2. go to https://techlauncher-mlai-edge-physics.github.io/ 
3. no output
4. profit

i get similar results when i run the website in a developer context (with `npm run dev`)

**Expected behavior**
The rest of the site content

**Screenshots**
![image](https://github.com/techlauncher-mlai-edge-physics/CFlowSim/assets/28855597/71d21c86-0fca-42f8-8185-6f1595281847)

**Desktop (please complete the following information):**

- OS: Arch Linux x86_64 `6.4.11-arch2-1` running on X11 display system
- Browser: firefox 
- Version 116.0.3 (64-bit)

**Task Relationship**
  Belongs to: #<--issue number-->
  Blocks: #<--issue number-->
  Blocked by: #<--issue number-->
  Subtasks: #<--issue number-->

**Comment by Lutra-Fs** [comment]
can not replicate in Firefox 117.0.1 (the most recent stable version) on Windows, maybe a Linux-specific issue.

**Comment by esterTion** [comment]
Turns out it's because `node_modules/three/examples/jsm/capabilities/WebGPU.js` is doing WebGPU detection in the global scope. It is expecting `navigator.gpu` to be `undefined` or `navigator.gpu.requestAdapter()` returns a `null` for not supporting WebGPU. 
However, currently in firefox release version, when user turns on `dom.webgpu.enabled`, `navigator.gpu` is not `undefined` but `navigator.gpu.requestAdapter()` throws an exception, which blocks all other codes from continuing. 

This issue is beyond our control. We can't avoid importing `capabilities/WebGPU.js` cause it is imported from `WebGPURenderer`. The only applicable fix for now is turn off `dom.webgpu.enabled` in the firefox config.

**Comment by Lutra-Fs** [comment]
see https://github.com/gpuweb/gpuweb/wiki/Implementation-Status#firefox, Firefox has `dom.webgpu.enabled` turned off by default in the release/beta version and this should not be changed
