### ISSUE TITLE
implement popup to save model state when user exits website

### ISSUE THREAD

**Issue by peipacut** [techlauncher-mlai-edge-physics/CFlowSim#95]

**Comment by peipacut** [comment]
user story points: 3(?)

**Comment by Lutra-Fs** [comment]
#104

**Comment by LorenzoValentine** [comment]
To implement these codes, I use the `useEffect` hook to add and remove an event listener for the `beforeunload` event. This event is triggered when the user is about to leave the current page or close the browser tab. 
However, due to technical difficulties, Chrome and Firefox is unable to set custom information to display in the pop-up.
